### ISSUE TITLE
is there a version of this that could work for iphone 11? 

### ISSUE THREAD

**Issue by yeetyboi-1991** [jsharkey13/iphone_backup_decrypt#12]

**Comment by jsharkey13** [comment]
For reference, it shouldn't matter what physical device it is, what matters is what iOS and iTunes version the backup is from!
I _think_ this code, like the StackOverflow code it is based on, works for iOS 11 backups and onwards, but it is a long time since I have had an encrypted iOS 11 backup to test it with.
