### ISSUE TITLE
CBC padding error

### ISSUE THREAD

**Issue by gmattos** [jsharkey13/iphone_backup_decrypt#15]
After executing the attempt of WhatsApp decrypting database method, I got the error message as described below:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\GM\Downloads\iphone_backup_decrypt-master\src\iphone_backup_decrypt\iphone_backup.py", line 272, in extract_file
    decrypted_data = self.extract_file_as_bytes(relative_path, domain)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GM\Downloads\iphone_backup_decrypt-master\src\iphone_backup_decrypt\iphone_backup.py", line 251, in extract_file_as_bytes
    return self.decrypt_inner_file(file_id=file_id, file_bplist=file_bplist)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GM\Downloads\iphone_backup_decrypt-master\src\iphone_backup_decrypt\iphone_backup.py", line 193, in decrypt_inner_file
    return google_iphone_dataprotection.removePadding(decrypted_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GM\Downloads\iphone_backup_decrypt-master\src\iphone_backup_decrypt\google_iphone_dataprotection.py", line 179, in removePadding
    raise Exception('Invalid CBC padding')
Exception: Invalid CBC padding 

Doing my troubleshooting research, I guess this error is related to the decryption process of whatsapp chatstorage.sqlite. I have successfully installed all dependencies except the fastpbkdf2, but as described in the readme file, it is optional to the code works.

I follow whatsapp development, and they have improved their encryption or security solutions yearly, unlike iTunes which doesn't change very often. Does this CBC padding error have a possible solution?

Also, can you please show a code example of how to decrypt Manifest.db? 

Thank you for the interesting project!

**Comment by jsharkey13** [comment]
A CBC padding error suggests that the file you're trying to decrypt isn't in the right format. This is unlikely to be to do with the decryption process, since the problem is with the encrypted file itself before this code touches it. Are you sure the backup is encrypted? If the backup is not encrypted, that could cause this error. Is it only one file that errors and others work, or do other files have the same issue?

The line numbers you have don't seem to match the latest from `master`; this error was quite common with a [really old version of the library](https://github.com/jsharkey13/iphone_backup_decrypt/commit/9b2e982be85f75b82c8a51fc4391ddfe66bcfe99). Could you try again specifically with the latest version [`v0.8.0`](https://github.com/jsharkey13/iphone_backup_decrypt/releases/tag/v0.8.0)? If you see the same error, then another stack trace would be useful.

As for extracting the Manifest file, it's really simple:
```python
from iphone_backup_decrypt import EncryptedBackup

backup = EncryptedBackup(..........)
backup.save_manifest_file("./output/Manifest.sqlite")
```
